# Generated by Django 3.0.3 on 2020-04-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20200226_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='popularity',
            field=models.PositiveIntegerField(default=0, verbose_name='Popularity'),
        ),
    ]
